const { test, expect } = require('@playwright/test')
const { seedDatabase, loginWith, createBook } = require('./helper')
test.beforeEach(async ({ request }) => { await seedDatabase(request) })
test('a second browser receives subscriptions and refreshes an already cached genre', async ({ browser, page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'books', exact: true }).click()
  await page.getByRole('button', { name: 'classic', exact: true }).click()
  await expect(page.getByText('Crime and punishment')).toBeVisible()
  const context = await browser.newContext()
  const writer = await context.newPage()
  try {
    await writer.goto('http://localhost:5173')
    await loginWith(writer, 'testuser', 'secret')
    await expect(writer.getByRole('button', { name: 'logout' })).toBeVisible()
    await createBook(writer, { title: 'Live classic book', author: 'Live Author', published: 2026, genres: ['classic'] })
    await expect(page.getByRole('status')).toContainText('A new book was added to the library.')
    await expect(page.getByRole('cell', { name: 'Live classic book', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'all genres', exact: true }).click()
    await expect(page.getByRole('cell', { name: 'Live classic book', exact: true })).toHaveCount(1)
  } finally { await context.close() }
})
test('recommendations refresh after adding to a previously viewed favorite genre', async ({ page }) => {
  await page.goto('/')
  await loginWith(page, 'testuser', 'secret')
  await expect(page.getByRole('button', { name: 'logout' })).toBeVisible()
  await page.getByRole('button', { name: 'recommend', exact: true }).click()
  await expect(page.getByText('Clean Code')).toBeVisible()
  await createBook(page, { title: 'New favorite book', author: 'Favorite Author', published: 2026, genres: ['refactoring'] })
  await expect(page.getByText('Book saved', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'recommend', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'New favorite book', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'logout' }).click()
  await expect(page.getByRole('button', { name: 'login' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'recommend' })).not.toBeVisible()
})
